schemaVersion: 2.2.0
metadata:
  name: empty-wnuk
  namespace: che-kube-admin-devspaces-4m78o2
components:
  - name: universal-developer-image
    container:
      image: registry.redhat.io/devspaces/udi-rhel8@sha256:9199796c9dd82a16ebb2c4ff8d06b9727f392eb93eb7ffa2974ad6c16e3d8e5d
      command:
        - /bin/bash
        - -c
        - |
          # operator-sdk のバイナリを /home/user/.local/bin にインストール
          mkdir -p /home/user/.local/bin
          curl -L https://github.com/operator-framework/operator-sdk/releases/download/v1.25.0/operator-sdk_linux_amd64 -o /home/user/.local/bin/operator-sdk
          chmod +x /home/user/.local/bin/operator-sdk
          echo "operator-sdk installed to /home/user/.local/bin"
