schemaVersion: 2.2.0
metadata:
  name: empty-wnuk
  namespace: che-kube-admin-devspaces-4m78o2
components:
  - name: universal-developer-image
    container:
      image: registry.redhat.io/devspaces/udi-rhel8@sha256:9199796c9dd82a16ebb2c4ff8d06b9727f392eb93eb7ffa2974ad6c16e3d8e5d
      command:
        - /bin/sh
        - -c
        - |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac) &&\
          export OS=$(uname | awk '{print tolower($0)}') &&\
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.37.0 &&\
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH} &&\
          mkdir -p /home/user/.local/bin &&\
          chmod +x operator-sdk_${OS}_${ARCH} &&\ 
          mv operator-sdk_${OS}_${ARCH} /home/user/.local/bin/operator-sdk
